import "mocha";
import expect from "expect.js";
import { Base64 } from "js-base64";

import { isValidIPS } from "./ips";

const sampleBase64IPS =
  "UEFUQ0gAAAkAAU4AAAsAAUcAAQQACgEQzu8AAESqAHQAAQ8AAxgRlQABEwABNAABFQAFGgDVACIAARsAGWlv9vdzCZDhEERAmpDV0EQwqSFdSCLg+GAAAU4AAisZAAFYAAFOAAFaAAFHAAFeAAHHAAFgAAFOAAFuAAEBAAFwAAFOAALPAAFOAALWAAHfAALYAAFOAAObAAFOAAOdAAFHAASEAAFOAASGAAFHAASYAAGHAASaAAFOAASmAAHHAASoAAFOAAVhAAHfAAVjAAFOAAWMAAHfAAWOAAFOAAdVAAFOAAdXAAFHAAh2AAHAAAiBAAGfAAiDAAFOAAqXAAFHAAqkAAHfAAqmAAFOAArfAAHfAArhAAFOAAzxAAFHAB0jAAEkAB7ZAAFOAB7zAAFOACGLAAHCACHKAAHOACtUAAGOAEObAAHCAEQRAAHCAEUgAAHOAEWVAAGOAEYPAAHOAEa2AAGOAFJ+AAHCAFMXAAHCAFRZAAHOAFTRAAGOAF2bAAHCAF3jAAHOAF6UAAHCAF69AAHOAGHhAAGOAGL5AAGOAGQVAAHCAGRPAAHOAGSyAAHCAGTbAAHOAGZcAAGOAGdLAAGOAGiKAAHCAGjSAAHOAGkIAAHCAGk/AAHOAG08AAGOAG40AAGOAIANAAHCAIMNAAHCAINaAAHOAIQeAAGOAISIAAGOAIdaAAHCAIxmAAHCAIzFAAHCAM+WAAHCANH0AAHCANNtAAHCRU9G";
const sampleByteArrayIPS = Base64.toUint8Array(sampleBase64IPS);

describe("isValidIPS", () => {
  it("validates header", () => {
    expect(isValidIPS(sampleByteArrayIPS)).to.eql(true);
  });
});
