name: Create patches.json

on:
#   schedule:
#     - cron:  '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install

      - name: Create patches.json
        run: node scrape.mjs
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.1
        with:
          add: 'public/patches/pocket.js'

